### ISSUE TITLE
Halt / Up != rerunning puppet

### ISSUE THREAD

**Issue by lonnen** [rhelmer/socorro-vagrant#11]
`sudo /opt/ruby/bin/puppet /vagrant/manifests/init.pp` will rerun puppet from within the VM, but this isn't sufficient for applying changes to the mware. I need to exit the VM, halt it, and run `vagrant up` to actually get the code changes to take effect. Maybe I need to explicitly restart apache2?

**Comment by rhelmer** [comment]
Yes I bet it's doing "refresh" on Apache when necessary, which is probably "reload" not "restart" (need a full restart to make sure all mod_wsgi processes are shut down).

Generally instead of rerunning puppet in my VM, I just do "make deploy" and then explicitly restart apache and/or supervisord, depending on what I changed.

To make puppet do this automatically we should have a supervisord and apache restart happen anytime the "socorro-install" rule runs (which is on every puppet reload right now).

**Comment by lonnen** [comment]
Ok. From the readme I thought that's what was happening already: 

`Alternatively, you may rerun puppet (which will run "make install" and automatically restart any
services as-needed):`

**Comment by rhelmer** [comment]
Yeah it's a bug :)

**Comment by rhelmer** [comment]
Fixed as part of this pull request https://github.com/mozilla/socorro/pull/434
