### ISSUE TITLE
socorro-vagrant should install local configman too

### ISSUE THREAD

**Issue by peterbe** [rhelmer/socorro-vagrant#14]
Just like we're installing isodate from pypi we should also install configman from the submodule configman/ inside the socorro root. 

In fact, I don't know how you prefer it installed; it just needs to be installed :)

**Comment by rhelmer** [comment]
Hmm so if we want to install from the submodule in the socorro root, rather than doing "sudo pip install" (as isodate is installed now) I think we'd want something like:

submodule init
submodule update
cd configman
sudo python setup.py install

However since vagrant does "make install" to /data/socorro, we could install it in there (similar to the "thirdparty" directory) and make sure it's on the PYTHONPATH (I think it would be without us doing anything special actually). 

It could in fact be in the "thirdparty" directory, although really I'd rather just get rid of that directory instead, it's from ancient times.

**Comment by peterbe** [comment]
The above is (almost) correct.:

```
git submodule update --init --recursive
cd configman
sudo python setup.py install
```

We can't use thirdparty because the configman base directory isn't a module. It's just a directory that contains things like the README, setup.py, LICENSE, etc. (no **init**.py) and just happens to be called the same as the python module it contains. So, if we make its parent available in sys.path we'd have to refer to it as `import configman.configman`.

**Comment by rhelmer** [comment]
This is done by the same work we did to get it into socorro (bug 721134)
