### ISSUE TITLE
Installing PostgreSQL 9 instead of 8

### ISSUE THREAD

**Issue by adngdb** [rhelmer/socorro-vagrant#2]
To install it on Ubuntu 11.04:
sudo add-apt-repository ppa:pitti/postgresql
sudo apt-get update
sudo apt-get install postgesql-9.0

**Comment by rhelmer** [comment]
Thanks, will add to the puppet manifests!

Did this migrate your existing DB over and allow you to use https://wiki.mozilla.org/ExtractDBscript#loadExtractDB.py ok?

**Comment by adngdb** [comment]
No, not yet, but I'm trying to find a way to have it working... If I cannot
find anything by tomorrow, could you please update the puppet manifest so it
uses postgres 9?

On Wed, Jun 1, 2011 at 6:10 PM, rhelmer <
reply@reply.github.com>wrote:

> Thanks, will add to the puppet manifests!
> 
> Did this migrate your existing DB over and allow you to use
> https://wiki.mozilla.org/ExtractDBscript#loadExtractDB.py ok?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rhelmer/socorro-vagrant/issues/2#comment_1278378

## 

Adrian Gaudebert
WebDev Intern @ Mozilla
http://adrian.gaudebert.fr

**Comment by rhelmer** [comment]
Running a test on this overnight so haven't merged to master, but I think this will do it: https://github.com/rhelmer/socorro-vagrant/commit/631ca732b38175cedbc30f0e284aaea48727468b

**Comment by rhelmer** [comment]
after some testing and a little more tweaking, pushed to master in https://github.com/rhelmer/socorro-vagrant/commit/9d7ed372f92a851d93ac5840318c47fcffa39309 and https://github.com/rhelmer/socorro-vagrant/commit/631ca732b38175cedbc30f0e284aaea48727468b

I suggest doing "git pull && vagrant destroy && vagrant up" to rebuild the VM from a clean slate (rather than "vagrant reload" which simply runs puppet again and would leave bits of the old postgres 8.x install around).
