### ISSUE TITLE
Couldn't find package Postgresql-9.0 

### ISSUE THREAD

**Issue by lonnen** [rhelmer/socorro-vagrant#4]
err: /Stage[main]/Socorro-db/Package[postgresql-9.0]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install postgresql-9.0' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Couldn't find package postgresql-9.0

Causes a bunch of skips because of failed dependencies, all related to postgres extensions, languages, db creation, etc.

**Comment by lonnen** [comment]
It looks like the ppa was updated to postgresql-9.1. Changing that in db.pp uncovers new errors, but PostgreSQL successfully installs.

**Comment by lonnen** [comment]
postgresql-9.0 was reintroduced in the ppa.

**Comment by MatterGrey** [comment]
This bug would appear to be back.

**Comment by rhelmer** [comment]
@MatterGrey it is, but we don't really use this repo anymore, it's integrated with socorro now.

The problem is that we need to upgrade to Postgres 9+ (probably going to jump straight to 9.2), since the Ubuntu version our vagrant uses is going to be unsupported soon (and never directly supported PG 9.0, only via PPA which the owner wants to stop maintaining)
